name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Prepare reports folder
        run: mkdir -p reports

      - name: Run Postman collection - Login
        continue-on-error: true
        run: |
          newman run tests/toolshop.postman_collection.json \
            --folder "Users - Login" \
            --iteration-data tests/login.csv \
            --environment tests/environment.json \
            --export-environment tests/environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export reports/test-report-login.html

      - name: Run Postman collection - Product Search
        continue-on-error: true
        run: |
          newman run tests/toolshop.postman_collection.json \
            --folder "Products - Search" \
            --iteration-data tests/product_search.csv \
            --environment tests/environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export reports/test-report-search.html

      - name: Run Postman collection - Product By ID
        continue-on-error: true
        run: |
          newman run tests/toolshop.postman_collection.json \
            --folder "Products - Get by Id" \
            --iteration-data tests/product_by_id.csv \
            --environment tests/environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export reports/test-report-getid.html

      # Artifacts để xem trong PR / Actions
      - name: Upload Test Reports (Artifacts)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: reports/*.html
          if-no-files-found: warn

      # --- Deploy GitHub Pages (chỉ khi push main) ---
      - name: Configure GitHub Pages
        if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/configure-pages@v5

      - name: Prepare Pages content
        if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        shell: bash
        run: |
          set -e
          mkdir -p public
          shopt -s nullglob
          cp -r reports/*.html public/ 2>/dev/null || true

          # Tạo index liệt kê link tới tất cả report
          {
            echo '<html><head><meta charset="utf-8"><title>API Test Reports</title></head><body><h1>API Test Reports</h1><ul>'
            for f in public/*.html; do
              base="$(basename "$f")"
              [[ "$base" == "index.html" ]] || echo "<li><a href=\"$base\">$base</a></li>"
            done
            echo '</ul></body></html>'
          } > public/index.html

          echo "Files to publish:"
          ls -lah public || true

      - name: Upload Pages artifact
        if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@v4
