name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection - Login
        run: |
          newman run tests/toolshop.postman_collection.json             --folder "Users - Login"             --iteration-data tests/login.csv             --environment tests/environment.json             --reporters cli,htmlextra             --reporter-htmlextra-export test-report-login.html

      - name: Run Postman collection - Product Search
        run: |
          newman run tests/toolshop.postman_collection.json             --folder "Products - Search"             --iteration-data tests/product_search.csv             --environment tests/environment.json             --reporters cli,htmlextra             --reporter-htmlextra-export test-report-search.html

      - name: Run Postman collection - Product By ID
        run: |
          newman run tests/toolshop.postman_collection.json             --folder "Products - Get by Id"             --iteration-data tests/product_by_id.csv             --environment tests/environment.json             --reporters cli,htmlextra             --reporter-htmlextra-export test-report-getid.html

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: "*.html"
